### Variables
@baseUrl = http://localhost:5000
@contentType = application/json

### GET request to home endpoint
GET {{baseUrl}}
###

### GET request to test endpoint
GET {{baseUrl}}/test
###

### GET request to fetch all users (test-route)
GET {{baseUrl}}/users

### POST request to create a new user (test-route)
POST {{baseUrl}}/users-create
Content-Type: {{contentType}}

{
  "name": "new user",
  "email": "new2@gmail.com"
}

### PATCH request to update user (test-route)
PATCH {{baseUrl}}/users-update
Content-Type: {{contentType}}

{
  "id": "487c5027-74f0-4419-b180-c7d95876da44",
  "name": "new user 2 Updated",
  "email": "new2@gmail.com"
}

### DELETE request to delete user (test-route)
DELETE {{baseUrl}}/users-delete/487c5027-74f0-4419-b180-c7d95876da44