### Variables
@baseUrl = http://localhost:5000
@contentType = application/json

### GET request to home endpoint
GET {{baseUrl}}
###

### GET request to create a new user (test-route)
POST {{baseUrl}}/users-create
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "johndoe@gmail.com"
}